package com.inkt.remotekeyboard.ui.theme

import androidx.compose.ui.graphics.Color

// MiuiX Light Colors
val MiuiLightPrimary = Color(0xFF0061E4)
val MiuiLightOnPrimary = Color(0xFFFFFFFF)
val MiuiLightPrimaryContainer = Color(0xFFD8E2FF)
val MiuiLightOnPrimaryContainer = Color(0xFF001A41)
val MiuiLightSecondary = Color(0xFF565E71)
val MiuiLightOnSecondary = Color(0xFFFFFFFF)
val MiuiLightSecondaryContainer = Color(0xFFDAE2F9)
val MiuiLightOnSecondaryContainer = Color(0xFF131C2B)
val MiuiLightTertiary = Color(0xFF6E5676)
val MiuiLightOnTertiary = Color(0xFFFFFFFF)
val MiuiLightTertiaryContainer = Color(0xFFF7D8FF)
val MiuiLightOnTertiaryContainer = Color(0xFF27132F)
val MiuiLightBackground = Color(0xFFF8F9FF)
val MiuiLightOnBackground = Color(0xFF191C20)
val MiuiLightSurface = Color(0xFFF8F9FF)
val MiuiLightOnSurface = Color(0xFF191C20)
val MiuiLightSurfaceVariant = Color(0xFFE0E2EC)
val MiuiLightOnSurfaceVariant = Color(0xFF44474E)
val MiuiLightError = Color(0xFFBA1A1A)
val MiuiLightOnError = Color(0xFFFFFFFF)
val MiuiLightOutline = Color(0xFF74777F)
val MiuiLightSurfaceContainerLow = Color(0xFFF1F3FA)
val MiuiLightSurfaceContainer = Color(0xFFECEDF4)
val MiuiLightSurfaceContainerHigh = Color(0xFFE6E8EF)

// MiuiX Dark Colors
val MiuiDarkPrimary = Color(0xFFADC6FF)
val MiuiDarkOnPrimary = Color(0xFF003063)
val MiuiDarkPrimaryContainer = Color(0xFF00468C)
val MiuiDarkOnPrimaryContainer = Color(0xFFD8E2FF)
val MiuiDarkSecondary = Color(0xFFBEC6DC)
val MiuiDarkOnSecondary = Color(0xFF283041)
val MiuiDarkSecondaryContainer = Color(0xFF3E4759)
val MiuiDarkOnSecondaryContainer = Color(0xFFDAE2F9)
val MiuiDarkTertiary = Color(0xFFDBBCE3)
val MiuiDarkOnTertiary = Color(0xFF3D2845)
val MiuiDarkTertiaryContainer = Color(0xFF553F5C)
val MiuiDarkOnTertiaryContainer = Color(0xFFF7D8FF)
val MiuiDarkBackground = Color(0xFF111318)
val MiuiDarkOnBackground = Color(0xFFE2E2E9)
val MiuiDarkSurface = Color(0xFF111318)
val MiuiDarkOnSurface = Color(0xFFE2E2E9)
val MiuiDarkSurfaceVariant = Color(0xFF44474E)
val MiuiDarkOnSurfaceVariant = Color(0xFFC4C6D0)
val MiuiDarkError = Color(0xFFFFB4AB)
val MiuiDarkOnError = Color(0xFF690005)
val MiuiDarkOutline = Color(0xFF8E9099)
val MiuiDarkSurfaceContainerLow = Color(0xFF191C20)
val MiuiDarkSurfaceContainer = Color(0xFF1D2024)
val MiuiDarkSurfaceContainerHigh = Color(0xFF282A2F)
